### ISSUE TITLE
Unable to Assign Negative Emitter Mass

### ISSUE THREAD

**Issue by WildKarrde1138** [seedhartha/kotorblender#13]
Some vanilla models, such as 101PER2a from TSL, use bubble emitters with negative Mass values.  KOTORBlender currently only allows positive Masses, so importing and reexporting these models makes it so that the bubbles hang around their emitter point and don’t float up very far.

**Comment by seedhartha** [comment]
Should be fixed starting [version 3.7.1](https://deadlystream.com/files/file/1853-kotorblender-for-blender-33/?changelog=0).
