### ISSUE TITLE
"List index is out of range"

### ISSUE THREAD

**Issue by HdotAdotSdot** [seedhartha/kotorblender#14]
"List index is out of range" error when exporting mdl after creating a face from automatically merged similar vertices.

**Comment by HdotAdotSdot** [comment]
![1](https://github.com/seedhartha/kotorblender/assets/154993139/5fc93a9e-a4cf-41aa-bcd6-3c611cbc5f79)
![2](https://github.com/seedhartha/kotorblender/assets/154993139/aedebe75-e636-4220-ad31-5ed5460df468)
![3](https://github.com/seedhartha/kotorblender/assets/154993139/c40e990d-0ec7-4930-9bd7-119337b952d4)

**Comment by seedhartha** [comment]
Is that existing or a new model? Please provide either model name or model file.

**Comment by HdotAdotSdot** [comment]
[w_vbroswrd_001.zip](https://github.com/seedhartha/kotorblender/files/13779290/w_vbroswrd_001.zip)
![4](https://github.com/seedhartha/kotorblender/assets/154993139/f8b04d57-8613-4449-b8de-d9a5c069b33f)

**Comment by HdotAdotSdot** [comment]
[Export.zip](https://github.com/seedhartha/kotorblender/files/13779325/Export.zip)

**Comment by seedhartha** [comment]
I was able to replicate the issue. I think it is due to the new face being a quad, not a triangle. As a workaround, select a face and triangulate it.
![Screenshot 2023-12-27 144339](https://github.com/seedhartha/kotorblender/assets/7695218/a9bedbc6-9afb-45a4-88cc-e08c671f0198)

**Comment by HdotAdotSdot** [comment]
It worked, thanks for the answer

**Comment by seedhartha** [comment]
Properly fixed by 1a675181dca85084f893b97668ea5d23b8a0b964, thanks for reporting!
