### ISSUE TITLE
Properly package .zip file so that it can be installed using the Blender addon GUI

### ISSUE THREAD

**Issue by zocker-160** [seedhartha/kotorblender#6]
The current zip file available for download cannot be installed using the Blender addon GUI (with the `Install...` button).
I think that expecting the ppl to unpack and install the addon manually into the right directory is not a good solution, especially because it can be fixed easily.

If you are interested I would be willing to create a PR that fixes this issue.

**Comment by seedhartha** [comment]
Probably not relevant to you anymore, but a PR would be welcome. Personally, current approach meets my needs, so I don't have much incentive to investigate this.
