### ISSUE TITLE
Exporting kotor models in other formats glitched

### ISSUE THREAD

**Issue by Jonspeeth** [seedhartha/kotorblender#9]
The models when exported, have a .mtl file that doesn't texture it correctly. I'm trying to export the maps into Unity for mods, but It doesn't work correctly.

**Comment by seedhartha** [comment]
Kotor material system is rather complicated, a lot of it comes from TXI files, which I do not import in KB. It is no wonder that things like envmaps and transparency are not properly rendered or exported to other formats. Not something that I'm interested in fixing at the moment.

**Comment by Jonspeeth** [comment]
I would pay for you to fix that, as it would save my sanity exporting the KotOR maps into Unity for Blade & Sorcery mods (I've done several maps already, and it's a nightmare texturing by hand)
